# on:
#   push:
#     branches:
#       - "develop"
#       - "master"

# env:
#   GO_VERSION: "1.16"

# jobs:
#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Checkout"
#         uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: ${{ env.GO_VERSION }}
#       - name: "Pull dependencies"
#         run: go mod vendor
#       - name: "Unit tests"
#         run: make test
#       - name: "Linter"
#         run: make lint
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - name: "Checkout"
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: "Calculate semver tag"
#         id: semver-tag
#         uses: gandarez/semver-action@feature/resync
#         with:
#           debug: true
#       - name: Changelog
#         uses: gandarez/changelog-action@v1.0.4
#         id: changelog
#         with:
#           current_tag: ${{ github.sha }}
#           previous_tag: ${{ steps.semver-tag.outputs.ancestor_tag }}
#           exclude: |
#             ^Merge pull request .*
#           debug: true
#       - shell: bash
#         run: |
#           mkdir release
#           expr 3 + 7 > ./release/math.txt
#       - uses: gandarez/gh-find-current-pr@v1.1.0
#         id: changelog-release
#       - name: Prepare changelog for release
#         id: changelog-release-cleaned
#         shell: bash
#         run: |
#           changelog=$(sed -n '/changelog:/I,$p' ${{ steps.changelog-release.outputs.body }} | tail -n +3)
#           echo "::set-output name=changelog::$changelog"
#       # - name: "Create Tag" # Because draft release don't create the tag until it gets published
#       #   uses: actions/github-script@v4
#       #   with:
#       #     github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
#       #     script: |
#       #       github.git.createRef({
#       #         owner: context.repo.owner,
#       #         repo: context.repo.repo,
#       #         ref: "refs/tags/${{ steps.semver-tag.outputs.semver_tag }}",
#       #         sha: context.sha
#       #       })
#       - name: "Create Release"
#         uses: softprops/action-gh-release@v1
#         with:
#           name: ${{ steps.semver-tag.outputs.semver_tag }}
#           tag_name: ${{ steps.semver-tag.outputs.semver_tag }}
#           body: ${{ steps.changelog-release-cleaned.outputs.changelog }}
#           prerelease: ${{ steps.semver-tag.outputs.is_prerelease }}
#           files: ./release/*
#         env:
#           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
