on:
  release:
    types: [published]

env:
  GO_VERSION: "1.16"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Get the version"
        id: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: echo "${{ steps.version.outputs.version }}"
